services:
  mysql:
    container_name: mysql
    image: mysql:8
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: store
      MYSQL_USER: me
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - store-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  store_app:
    container_name: store_app
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    environment:
      DB_USER: me
      DB_PASSWORD: password
      DB_URL: jdbc:mysql://mysql:3306/store?useSSL=false&allowPublicKeyRetrieval=true
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - store-network

networks:
  store-network:
    driver: bridge

volumes:
  mysql: