spring:
  application:
    name: Store-app
  datasource:
    username: ${DB_USER:restadmin}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:mysql://mysql:3306/store}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto:
      create
server:
  servlet:
    context-path: "/store"
reset-code:
  expiration-time: PT7M


app:
  rate-limit:
    enabled: true
    max-requests: 5
    refill-period: PT20M
    cleanup-interval: PT30M
    excluded-paths:
      - "/register"
      - "/forgot-password"